name: mlewp-chapter03
channels:
  - conda-forge
dependencies:
  - pip=23.1.2
  - python=3.10.8
  - pip:
      - typing_extensions==4.15.0
      - numpy==2.2.6
      - scikit-learn==1.7.2
      - optuna==4.5.0
      - hyperopt==0.2.7
      - mlflow==3.4.0

